### ISSUE TITLE
Callable SlugLinks

### ISSUE THREAD

**Issue by BerkantC** [tecnocen-com/yii2-roa#13]
Propongo que se dé soporte para llamar un callable con los links por default, y asi poder modificarlos, Por ejemplo: 

`'slugLinks' => function ($links) {
$links['hola mundo'] = $this->establecimiento->getSelfLink() . '/estadisticas',
return $links;
}
`

**Comment by Faryshta** [comment]
¿Cómo propones editar el funcionamiento de `selfLink`?

**Comment by Faryshta** [comment]
Fixed with https://github.com/tecnocen-com/yii2-roa/commit/af4bdc69ce4eb60f043e03c49c8e809a20313104

```php
class Item extends ActiveRecord
{
     public function behaviors()
     {
           return [
               'slug' => [
                   'class' => Slug::class,
                   'resourceName' => 'item'
               ]
          ];
     }

    public function getSelfLink()
    {
         return $this->getBehavior('slug')->getSelfLink();
    }

    public function getSlugLinks()
    {
         return $this->getBehavior('slug')->getSlugLinks();
    }
}
```

The methods `getSelfLink()` and `getSlugLinks()` can be rewritten freely.
