### ISSUE TITLE
https getSelfLink

### ISSUE THREAD

**Issue by neverabe** [tecnocen-com/yii2-roa#19]
When i use https in the api, al self links returns http, instead https

**Comment by Faryshta** [comment]
can't reproduce it. you have a working example?

**Comment by neverabe** [comment]
The error occurs when i enable HTTPS with cloudflare, if you want i will send you a domain with the error.

**Comment by Faryshta** [comment]
Unrelated to this library, configure `yii\web\UrlManager`
