### ISSUE TITLE
Agregar Perfil Resource

### ISSUE THREAD

**Issue by Seether69** [tecnocen-com/yii2-roa#3]
Buen Día

Solicito agregar el resource Perfil con el motivo de que se pueda acceder a la información de usuario al token generado y que se pueda editar mediante el método PATCH

Saludos

**Comment by Faryshta** [comment]
i published and advance on this issue you can use GET requests now with the ProfileResource class

**Comment by Faryshta** [comment]
Profile resource can be created now using the classes `tecnocen\roa\controllers\ProfileResource` and `tecnocen\roa\urlRules\SingleRecord`
