### ISSUE TITLE
What is ROA application??

### ISSUE THREAD

**Issue by lubosdz** [tecnocen-com/yii2-roa#39]
What is a `ROA application` ?
A little update in README would help :-)

**Comment by Faryshta** [comment]
How about using this definition? https://whatis.techtarget.com/definition/resource-oriented-architecture-ROA

> A resource-oriented architecture (ROA) is the structural design supporting the internetworking of resources. A resource, in this context, is any entity that can be identified and assigned a uniform resource identifier (URI).

Thats the simplest definition I could find. I would prefer to change 'internetworking' with the an explanation of HAL but that would make it very difficult to understand.
